### ISSUE TITLE
List of news [user name not render properly]

### ISSUE THREAD

**Issue by BAXYac** [BAXYac/Polmeme#10]
kiedy nazwa użytkownika jest zbyt długa wyskakuje błąd renderingu (pszczółka)

zamiast tego gdy nazwa jest zbyt długa to powinny być trzy kropki (...)

przydatny link - > https://stackoverflow.com/questions/44579918/flutter-wrap-text-on-overflow-like-insert-ellipsis-or-fade

**Comment by katskoru** [comment]
problem rozwiązany
