### ISSUE TITLE
news don't load automatically 

### ISSUE THREAD

**Issue by BAXYac** [BAXYac/Polmeme#11]
newsy nie wczytują się automatycznie. Trzeba najpierw kliknąć coś w appce (ustawienia albo meme) by newsy się zaciągnęły,

pożądany efekt to taki, że jeżeli czekamy aż newsy się zaciągną to user powinien mieć jakiś feedback  jak loading animation albo chociaż sam tekst 'Wczytuje'. 

przykład z flutter.dev

```
FutureBuilder(
  future: _future
  builder: (context, snapshot) {
    if (snapshot.hasData) {
      return Text(snapshot.data!.title);
    } else if (snapshot.hasError) {
      return Text('${snapshot.error}');
    }

    // By default, show a loading spinner.
    return const CircularProgressIndicator();
  },
)
```

**Comment by katskoru** [comment]
naprawione :)
